services:
  - type: web
    name: renewable-portfolio-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --config gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DASH_DEBUG
        value: false
      - key: WEB_CONCURRENCY
        value: 1 